name: Docker Flow Backend

on:
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.PROJ_USER }}
        password: ${{ secrets.PROJ_TOKEN }}
    - name: docker build image
      run: docker build -t aglanborg/proj-backend .
    - name: docker push image
      run: docker push aglanborg/proj-backend
